const DEFAULT_DOCUMENT_EMBEDDINGS_QUEUE_NAME = "document-embeddings"

export const DOCUMENT_EMBEDDINGS_QUEUE_NAME =
  process.env.DOCUMENT_EMBEDDINGS_QUEUE_NAME ?? DEFAULT_DOCUMENT_EMBEDDINGS_QUEUE_NAME
export const DOCUMENT_EMBEDDINGS_JOB_NAME = "create-embeddings"
