import { DOCUMENT_EMBEDDING_STATUS_CHANGED_CHANNEL_DTO } from "@caseai-connect/api-contracts"

export const DOCUMENT_EMBEDDING_STATUS_CHANGED_CHANNEL =
  DOCUMENT_EMBEDDING_STATUS_CHANGED_CHANNEL_DTO
