###

POST https://entreprise.francetravail.fr/connexion/oauth2/access_token?realm=%2Fpartenaire
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
    &client_id={{client_id}}
    &client_secret={{secret_key}}
    &scope=api_romeov2 o2dsoffre api_offresdemploiv2 api_evenementsv1 evenements
#    &scope=api_offresdemploiv2 o2dsoffre api_evenementsv1 evenements

###

POST https://api.francetravail.io/partenaire/romeo/v2/predictionMetiers
Accept: application/json
Content-Type: application/json
Authorization: Bearer 0ynEws6HL9vL4-VarvBJHGJgylA

{
  "appellations": [
    {
      "intitule": "métiers du jeu vidéo",
      "identifiant": "id1"
    }
  ],
  "options": {
    "nomAppelant": "caseai",
    "nbResultats": 5,
    "seuilScorePrediction": 0.7
  }
}
###

# curl --request GET
#  --url https://api.francetravail.io/partenaire/offresdemploi/v2/offres/search
#  --header 'Accept: application/json'
#  --header 'Authorization: Bearer 123'
GET https://api.francetravail.io/partenaire/offresdemploi/v2/offres/search?codeROME=M1405,M1419,M1811,M1409,M1422,K2402,K2401,M1402,M1429,M1702,M1403&departement=75&range=0-2
Accept: application/json
Authorization: Bearer s9jEVPrLxsYWuViAXEqXEJFvy8o

###
GET https://api.francetravail.io/partenaire/evenements/v1/salonsenligne
Accept: application/json
Authorization: Bearer ezbsR2CkLuKey_hNuh1adWJWSaE

###
POST https://api.francetravail.io/partenaire/evenements/v1/mee/evenements
Content-Type: application/json
Accept: application/json
Authorization: Bearer fGOGtWxrSjYkg3Gl_WA7ppudJ2k

{
  "dateFin": "2025-12-01",
  "departements": ["76"],
  "secteurActivite" : "M",
  "objectifs": [39]
}

###
GET https://api.francetravail.io/partenaire/evenements/v1/mee/tags/opera/lister
Content-Type:application/json
Accept:application/json
Authorization: Bearer ezbsR2CkLuKey_hNuh1adWJWSaE



###
GET https://api.data.inclusion.gouv.fr/api/v1/search/services?page=1&size=10&thematiques=logement-hebergement
Authorization: Bearer {{dataInclusionBearer}}
Content-Type:application/json
Accept:application/json

###
GET https://api.data.inclusion.gouv.fr/api/v1/search/services?page=1&size=20&thematiques=preparer-sa-candidature--realiser-un-cv-et-ou-une-lettre-de-motivation&code_commune=76540&exclure_doublons=true
Authorization: Bearer {{dataInclusionBearer}}
Content-Type:application/json
Accept:application/json


###
GET https://api.data.inclusion.beta.gouv.fr/api/v1/search/services?thematiques=mobilite--preparer-un-permis&code_commune=44109&size=20
Authorization: Bearer {{dataInclusionBearer}}
Content-Type:application/json
Accept:application/json


###
GET https://emplois.inclusion.beta.gouv.fr/api/v1/siaes?code_insee=44109&distance_max_km=5
Authorization: Bearer {{dataInclusionBearer}}
Content-Type:application/json
Accept:application/json


###
# curl -X 'GET'
#  'https://data.geopf.fr/geocodage/search?q=rouen&autocomplete=1&index=address&limit=10&returntruegeometry=false'
#  -H 'accept: application/json'
GET https://data.geopf.fr/geocodage/search?q=Sotteville&type=municipality
accept: application/json

###


# curl -s -X POST "https://api.notion.com/v1/databases/SESSIONS_DB_ID/query"
#  -H "Authorization: Bearer $NOTION_TOKEN"
#  -H "Notion-Version: 2022-06-28"
#  -H "Content-Type: application/json"
#  -d '{
#    "page_size": 100,
#    "sorts": [{ "property": "Date", "direction": "ascending" }]
#  }'
POST https://api.notion.com/v1/databases/e3b5ba04a6b94e6a845c604ae46bcee6/query
Authorization: Bearer {{notionSecret}}
Notion-Version: 2022-06-28
Content-Type: application/json

{
  "page_size": 100,
  "sorts": [
    {
      "property": "Date",
      "direction": "ascending"
    }
  ]
}

###

POST https://api.notion.com/v1/databases/29a7d19cc825808baa2dce8093f0dd59/query
Authorization: Bearer {{notionSecret}}
Notion-Version: 2022-06-28
Content-Type: application/json

{
  "page_size": 100,
  "filter": {
    "property": "Name",
    "title": { "contains": "Melvin" }
  }
}

###