name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on:
      labels: ubuntu-latest-m
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run tests
        run: TEST_WORKERS=2 make tests-parallel